name: Demo_CI_CD_Pipeline

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Debug files
        run: ls -R

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
            pip install -r requirements.txt || echo "No requirements file"
            pip install pytest  

  deploy-qa:
    needs: build-and-test
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest

    environment:
      name: qa

    steps:
      - name: Deploy to QA Server
        run: |
          echo "Deploying to QA server..."
          # Example:
          # scp -r . user@qa-server:/app
          # ssh user@qa-server "systemctl restart app"


  deploy-production:
    needs: build-and-test
    #if: github.ref == 'refs/heads/main'
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Deploy to Production Server
        run: |
          echo "Deploying to Production server..."
          # Example:
          # scp -r . user@prod-server:/app
          # ssh user@prod-server "systemctl restart app"